version: 0.2.0-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\termimage

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cp target\release\termimage.exe termimage-v0.2.0.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note termimage-v0.2.0.exe

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: termimage-v0.2.0.exe

deploy:
  provider: GitHub
  artifact: termimage-v0.2.0.exe
  auth_token:
    secure: 96bmaG3a5pos9Ew2qy6E8P6Wt0d80iAGK/8BKxSJkEonMARsbKMVf/zlDrvhKoiy
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
